name: global_configs
description: A flutter package to manage application configurations via singleton pattern.
version: 1.1.1
author: Mehdi Zarepour
homepage: https://github.com/mehdizarepour/flutter-global-configs
repository: https://github.com/mehdizarepour/flutter-global-configs

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  gato: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

 